name: Build & Push golang to Image Registry

on:
  push:
    branches:
      - golang
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      root_directory: ./
      work_directory: ./
      image_name: golang
